#!/usr/bin/env ruby

$LOAD_PATH << 'lib'

require 'sudoku'

def run(filename)
  solver = Sudoku::Grid.new(STDOUT)
  solver.ingest(filename)
  solver.safe_solve(:chains => true, :references => true)
end

run(ARGV.first)
